// AUTO-GENERATED by XOffset target-matrix signature exporter
// Platform: arm64_ios_clang (AArch64 iOS (Clang))
// Generated: committed baseline
//
// This file contains constexpr wire-ABI signature data for the v1 admitted catalog.
// Target ABI metadata comes from tools/signature_target_matrix.hpp.

#ifndef BOOST_TYPELAYOUT_SIG_ARM64_IOS_CLANG_HPP
#define BOOST_TYPELAYOUT_SIG_ARM64_IOS_CLANG_HPP

#include <boost/typelayout/tools/sig_types.hpp>

namespace boost { namespace typelayout { namespace platform {
namespace arm64_ios_clang {

// ---- Platform Metadata ----

inline constexpr const char platform_name[] = "arm64_ios_clang";
inline constexpr const char arch_prefix[] = "[64-le]";
inline constexpr std::size_t pointer_size      = 8;
inline constexpr std::size_t sizeof_long        = 8;
inline constexpr std::size_t sizeof_wchar_t     = 4;
inline constexpr std::size_t sizeof_long_double = 8;
inline constexpr std::size_t max_align          = 8;
inline constexpr const char data_model[]        = "LP64";

// ---- Type Signatures ----

// --- catalog.ScalarRecord ---
inline constexpr const char catalog_ScalarRecord_layout[] =
    "record[s:24,a:8]{@0:i32,@8:u64,@16:f64}";
inline constexpr bool catalog_ScalarRecord_byte_copy_safe = true;

// --- catalog.NestedValue ---
inline constexpr const char catalog_NestedValue_layout[] =
    "record[s:40,a:8]{@0:i32,@8:xstring[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32},@24:xvector[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32}<u16>}";
inline constexpr bool catalog_NestedValue_byte_copy_safe = true;

// --- catalog.WireCatalogRoot ---
inline constexpr const char catalog_WireCatalogRoot_layout[] =
    "record[s:144,a:8]{@0:enum<u32>,@4:array[2]<array[3]<i32>>,@32:xstring[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32},@48:xblob[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32},@64:xvector[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32}<i32>,@80:xvector[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32}<record[s:40,a:8]{@0:i32,@8:xstring[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32},@24:xvector[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32}<u16>}>,@96:xflatset[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32}<i32>,@112:xflatmap[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32}<i32,record[s:40,a:8]{@0:i32,@8:xstring[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32},@24:xvector[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32}<u16>}>,@128:xflatmap[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32}<xstring[s:16,a:8]{arena:rel32,data:rel32,size:u32,capacity:u32},i32>}";
inline constexpr bool catalog_WireCatalogRoot_byte_copy_safe = true;

// ---- Type Registry ----

inline constexpr ::boost::typelayout::TypeEntry types[] = {
    {"catalog.ScalarRecord", catalog_ScalarRecord_layout, catalog_ScalarRecord_byte_copy_safe},
    {"catalog.NestedValue", catalog_NestedValue_layout, catalog_NestedValue_byte_copy_safe},
    {"catalog.WireCatalogRoot", catalog_WireCatalogRoot_layout, catalog_WireCatalogRoot_byte_copy_safe},
};

inline constexpr std::size_t type_count = 3;

// ---- Platform Info Accessor ----

inline constexpr ::boost::typelayout::PlatformInfo get_platform_info() {
    return { platform_name, arch_prefix, types, type_count,
             pointer_size, sizeof_long, sizeof_wchar_t,
             sizeof_long_double, max_align, data_model };
}

}}}} // namespace boost::typelayout::platform::arm64_ios_clang

#endif // BOOST_TYPELAYOUT_SIG_ARM64_IOS_CLANG_HPP
