// AUTO-GENERATED by XOffset target-matrix signature exporter
// Platform: arm64_ios_clang (AArch64 iOS (Clang))
// Generated: committed baseline
//
// This file contains constexpr signature data for the v1 admitted catalog.
// Target ABI metadata comes from tools/signature_target_matrix.hpp.

#ifndef BOOST_TYPELAYOUT_SIG_ARM64_IOS_CLANG_HPP
#define BOOST_TYPELAYOUT_SIG_ARM64_IOS_CLANG_HPP

#include <boost/typelayout/tools/sig_types.hpp>

namespace boost { namespace typelayout { namespace platform {
namespace arm64_ios_clang {

// ---- Platform Metadata ----

inline constexpr const char platform_name[] = "arm64_ios_clang";
inline constexpr const char arch_prefix[] = "[64-le]";
inline constexpr std::size_t pointer_size      = 8;
inline constexpr std::size_t sizeof_long        = 8;
inline constexpr std::size_t sizeof_wchar_t     = 4;
inline constexpr std::size_t sizeof_long_double = 8;
inline constexpr std::size_t max_align          = 8;
inline constexpr const char data_model[]        = "LP64";

// ---- Type Signatures ----

// --- Player ---
inline constexpr const char Player_layout[] =
    "[64-le]record[s:40,a:8]{@0:i32[s:4,a:4],@4:i32[s:4,a:4],@8:O(string|16|8),@24:O(vector|16|8)<i32[s:4,a:4]>}";
inline constexpr bool Player_byte_copy_safe = true;

// --- Item ---
inline constexpr const char Item_layout[] =
    "[64-le]record[s:32,a:8]{@0:i32[s:4,a:4],@4:i32[s:4,a:4],@8:i32[s:4,a:4],@16:O(string|16|8)}";
inline constexpr bool Item_byte_copy_safe = true;

// --- GameData ---
inline constexpr const char GameData_layout[] =
    "[64-le]record[s:80,a:8]{@0:i32[s:4,a:4],@4:i32[s:4,a:4],@8:f32[s:4,a:4],@16:O(string|16|8),@32:O(vector|16|8)<record[s:32,a:8]{@0:i32[s:4,a:4],@4:i32[s:4,a:4],@8:i32[s:4,a:4],@16:O(string|16|8)}>,@48:O(set|16|8)<i32[s:4,a:4]>,@64:O(map|16|8)<O(string|16|8),i32[s:4,a:4]>}";
inline constexpr bool GameData_byte_copy_safe = true;

// ---- Type Registry ----

inline constexpr ::boost::typelayout::TypeEntry types[] = {
    {"Player", Player_layout, Player_byte_copy_safe},
    {"Item", Item_layout, Item_byte_copy_safe},
    {"GameData", GameData_layout, GameData_byte_copy_safe},
};

inline constexpr std::size_t type_count = 3;

// ---- Platform Info Accessor ----

inline constexpr ::boost::typelayout::PlatformInfo get_platform_info() {
    return { platform_name, arch_prefix, types, type_count,
             pointer_size, sizeof_long, sizeof_wchar_t,
             sizeof_long_double, max_align, data_model };
}

}}}} // namespace boost::typelayout::platform::arm64_ios_clang

#endif // BOOST_TYPELAYOUT_SIG_ARM64_IOS_CLANG_HPP
