// AUTO-GENERATED by Boost.TypeLayout Signature Export Tool
// Platform: x86_64_linux_clang (x86-64 Linux (Clang))
// Generated: 2026-03-15T12:55:13Z
//
// This file contains constexpr signature data and can be compiled
// by any C++17 or later compiler. P2996 is NOT required.

#ifndef BOOST_TYPELAYOUT_SIG_X86_64_LINUX_CLANG_HPP
#define BOOST_TYPELAYOUT_SIG_X86_64_LINUX_CLANG_HPP

#include <boost/typelayout/tools/sig_types.hpp>

namespace boost { namespace typelayout { namespace platform {
namespace x86_64_linux_clang {

// ---- Platform Metadata ----

inline constexpr const char platform_name[] = "x86_64_linux_clang";
inline constexpr const char arch_prefix[] = "[64-le]";
inline constexpr std::size_t pointer_size      = 8;
inline constexpr std::size_t sizeof_long        = 8;
inline constexpr std::size_t sizeof_wchar_t     = 4;
inline constexpr std::size_t sizeof_long_double = 16;
inline constexpr std::size_t max_align          = 16;
inline constexpr const char data_model[]        = "LP64";

// ---- Type Signatures ----

// --- Player ---
inline constexpr const char Player_layout[] =
    "[64-le]record[s:72,a:8]{@0:i32[s:4,a:4],@4:i32[s:4,a:4],@8:O(string|32|8),@40:O(vector|32|8)<i32[s:4,a:4]>}";

// --- Item ---
inline constexpr const char Item_layout[] =
    "[64-le]record[s:48,a:8]{@0:i32[s:4,a:4],@4:i32[s:4,a:4],@8:i32[s:4,a:4],@16:O(string|32|8)}";

// --- GameData ---
inline constexpr const char GameData_layout[] =
    "[64-le]record[s:144,a:8]{@0:i32[s:4,a:4],@4:i32[s:4,a:4],@8:f32[s:4,a:4],@16:O(string|32|8),@48:O(vector|32|8)<record[s:48,a:8]{@0:i32[s:4,a:4],@4:i32[s:4,a:4],@8:i32[s:4,a:4],@16:O(string|32|8)}>,@80:O(set|32|8)<i32[s:4,a:4]>,@112:O(map|32|8)<O(string|32|8),i32[s:4,a:4]>}";

// ---- Type Registry ----

inline constexpr ::boost::typelayout::TypeEntry types[] = {
    {"Player", Player_layout},
    {"Item", Item_layout},
    {"GameData", GameData_layout},
};

inline constexpr std::size_t type_count = 3;

// ---- Platform Info Accessor ----

inline constexpr ::boost::typelayout::PlatformInfo get_platform_info() {
    return { platform_name, arch_prefix, types, type_count,
             pointer_size, sizeof_long, sizeof_wchar_t,
             sizeof_long_double, max_align, data_model };
}

}}}} // namespace boost::typelayout::platform::x86_64_linux_clang

#endif // BOOST_TYPELAYOUT_SIG_X86_64_LINUX_CLANG_HPP
