// demo.cpp - Type layout signature usage examples

#include <iostream>
#include <cstdint>
#include "../include/typelayout.hpp"

using namespace typelayout;

// ===========================================================================
// Example: Binding types to expected layout signatures
// ===========================================================================

// Define your data structures
struct Point { int32_t x, y; };
struct Player {
    uint64_t id;
    char name[32];
    Point pos;
    float health;
};

// Bind each type to its "golden" layout signature (generated by typelayout_tool)
// If layout changes (e.g., due to different compiler/platform), compilation fails!
TYPELAYOUT_BIND(Point, "struct[s:8,a:4]{@0[x]:i32[s:4,a:4],@4[y]:i32[s:4,a:4]}");
TYPELAYOUT_BIND(Player, "struct[s:56,a:8]{@0[id]:u64[s:8,a:8],@8[name]:bytes[s:32,a:1],@40[pos]:struct[s:8,a:4]{@0[x]:i32[s:4,a:4],@4[y]:i32[s:4,a:4]},@48[health]:f32[s:4,a:4]}");

// ===========================================================================
// Example: Layout compatibility between types
// ===========================================================================

struct Vec2 { int32_t x, y; };  // Same layout as Point
static_assert(signatures_match<Point, Vec2>(), "Point and Vec2 must have same layout");

// ===========================================================================
// Example: Portability checks (no platform-dependent types)
// ===========================================================================

static_assert(is_portable<Point>(), "Point must be portable");
static_assert(is_portable<Player>(), "Player must be portable");

// ===========================================================================
// Example: Using LayoutMatch concept as template constraint
// ===========================================================================

// Only accepts types with Point-compatible layout
template<typename T>
    requires LayoutMatch<T, "struct[s:8,a:4]{@0[x]:i32[s:4,a:4],@4[y]:i32[s:4,a:4]}">
void send_point(const T& p) {
    // Guaranteed: layout matches on all platforms
    std::cout << "Sending point-like data...\n";
    (void)p;
}

int main() {
    std::cout << "=== typelayout Demo ===\n\n";
    
    // 1. Display layout signatures
    std::cout << "--- Layout Signatures ---\n";
    std::cout << "Point:\n  " << get_layout_signature_cstr<Point>() << "\n\n";
    std::cout << "Player:\n  " << get_layout_signature_cstr<Player>() << "\n\n";
    
    // 2. Compare signatures
    std::cout << "--- Layout Compatibility ---\n";
    constexpr bool match = signatures_match<Point, Vec2>();
    std::cout << "Point and Vec2 layout match: " << (match ? "yes" : "no") << "\n\n";
    
    // 3. Primitive types
    std::cout << "--- Primitive Types ---\n";
    std::cout << "int32_t: " << get_layout_signature_cstr<int32_t>() << "\n";
    std::cout << "double:  " << get_layout_signature_cstr<double>() << "\n";
    std::cout << "void*:   " << get_layout_signature_cstr<void*>() << "\n\n";
    
    // 4. Template with layout constraint
    std::cout << "--- Template Constraint ---\n";
    Point p{10, 20};
    Vec2 v{30, 40};
    send_point(p);  // OK: Point matches required layout
    send_point(v);  // OK: Vec2 also matches required layout
    
    std::cout << "\nAll compile-time assertions passed!\n";
    return 0;
}