// Exports the exact v1 target-matrix wire-ABI baselines under tools/sigs/.

#include "signature_catalog.hpp"
#include "signature_target_matrix.hpp"

#include <boost/typelayout.hpp>
#include <boost/typelayout/tools/sig_export.hpp>

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <string>
#include <string_view>
#include <vector>

namespace {

using XOffsetDatastructure::is_v1_wire_admitted_v;

struct ExportedTypeEntry {
    std::string name;
    std::string guard_name;
    std::string wire_abi_signature;
    bool byte_copy_safe{};
};

std::string make_identifier(std::string_view value) {
    std::string out;
    out.reserve(value.size());
    for (char ch : value) {
        if (std::isalnum(static_cast<unsigned char>(ch))) {
            out.push_back(ch);
        } else {
            out.push_back('_');
        }
    }
    return out;
}

std::string make_upper_identifier(std::string_view value) {
    std::string out = make_identifier(value);
    std::transform(out.begin(), out.end(), out.begin(), [](unsigned char ch) {
        return static_cast<char>(std::toupper(ch));
    });
    return out;
}

std::string cxx_escape(std::string_view value) {
    std::string out;
    out.reserve(value.size());
    for (char ch : value) {
        switch (ch) {
            case '\\': out += "\\\\"; break;
            case '"': out += "\\\""; break;
            case '\n': out += "\\n"; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            default: out.push_back(ch); break;
        }
    }
    return out;
}

std::vector<ExportedTypeEntry> collect_exported_type_entries() {
    std::vector<ExportedTypeEntry> entries;
    xoffset::signature::visit_exported_types([&]<typename T>(const char* name) {
        static_assert(is_v1_wire_admitted_v<T>,
            "target-matrix signature export only supports v1-admitted root/data types");
        constexpr auto wire_sig = XOffsetDatastructure::wire_abi_signature<T>();
        entries.push_back({
            .name = name,
            .guard_name = make_identifier(name),
            .wire_abi_signature = std::string(std::string_view(wire_sig)),
            .byte_copy_safe = is_v1_wire_admitted_v<T>,
        });
    });
    return entries;
}

int write_target_signature_file(
    const std::filesystem::path& path,
    const xoffset::signature::SignatureTargetSpec& target,
    const std::vector<ExportedTypeEntry>& entries) {
    std::ofstream os(path, std::ios::trunc);
    if (!os.is_open()) {
        std::cerr << "Error: cannot write " << path << '\n';
        return 1;
    }

    const std::string guard =
        "BOOST_TYPELAYOUT_SIG_" + make_upper_identifier(target.platform_name) + "_HPP";

    os << "// AUTO-GENERATED by XOffset target-matrix signature exporter\n";
    os << "// Platform: " << target.platform_name << " (" << target.display_name << ")\n";
    os << "// Generated: committed baseline\n";
    os << "//\n";
    os << "// This file contains constexpr wire-ABI signature data for the v1 admitted catalog.\n";
    os << "// Target ABI metadata comes from tools/signature_target_matrix.hpp.\n\n";

    os << "#ifndef " << guard << '\n';
    os << "#define " << guard << "\n\n";
    os << "#include <boost/typelayout/tools/sig_types.hpp>\n\n";
    os << "namespace boost { namespace typelayout { namespace platform {\n";
    os << "namespace " << target.platform_name << " {\n\n";
    os << "// ---- Platform Metadata ----\n\n";
    os << "inline constexpr const char platform_name[] = \""
       << target.platform_name << "\";\n";
    os << "inline constexpr const char arch_prefix[] = \""
       << target.arch_prefix << "\";\n";
    os << "inline constexpr std::size_t pointer_size      = "
       << target.pointer_size << ";\n";
    os << "inline constexpr std::size_t sizeof_long        = "
       << target.sizeof_long << ";\n";
    os << "inline constexpr std::size_t sizeof_wchar_t     = "
       << target.sizeof_wchar_t << ";\n";
    os << "inline constexpr std::size_t sizeof_long_double = "
       << target.sizeof_long_double << ";\n";
    os << "inline constexpr std::size_t max_align          = "
       << target.max_align << ";\n";
    os << "inline constexpr const char data_model[]        = \""
       << target.data_model << "\";\n\n";
    os << "// ---- Type Signatures ----\n\n";

    for (const auto& entry : entries) {
        os << "// --- " << entry.name << " ---\n";
        os << "inline constexpr const char " << entry.guard_name << "_layout[] =\n";
        os << "    \"" << cxx_escape(entry.wire_abi_signature) << "\";\n";
        os << "inline constexpr bool " << entry.guard_name << "_byte_copy_safe = "
           << (entry.byte_copy_safe ? "true" : "false") << ";\n\n";
    }

    os << "// ---- Type Registry ----\n\n";
    os << "inline constexpr ::boost::typelayout::TypeEntry types[] = {\n";
    for (const auto& entry : entries) {
        os << "    {\"" << entry.name << "\", "
           << entry.guard_name << "_layout, "
           << entry.guard_name << "_byte_copy_safe},\n";
    }
    os << "};\n\n";
    os << "inline constexpr std::size_t type_count = " << entries.size() << ";\n\n";
    os << "// ---- Platform Info Accessor ----\n\n";
    os << "inline constexpr ::boost::typelayout::PlatformInfo get_platform_info() {\n";
    os << "    return { platform_name, arch_prefix, types, type_count,\n";
    os << "             pointer_size, sizeof_long, sizeof_wchar_t,\n";
    os << "             sizeof_long_double, max_align, data_model };\n";
    os << "}\n\n";
    os << "}}}} // namespace boost::typelayout::platform::"
       << target.platform_name << "\n\n";
    os << "#endif // " << guard << '\n';
    return os.good() ? 0 : 1;
}

int export_target_matrix(const std::filesystem::path& dir) {
    std::filesystem::create_directories(dir);
    const auto entries = collect_exported_type_entries();

    std::vector<std::filesystem::path> expected_paths;
    expected_paths.reserve(xoffset::signature::target_matrix.size());
    for (const auto& target : xoffset::signature::target_matrix) {
        auto path = dir / (std::string(target.platform_name) + ".sig.hpp");
        expected_paths.push_back(path);
        const int status = write_target_signature_file(path, target, entries);
        if (status != 0) {
            return status;
        }
    }

    for (const auto& entry : std::filesystem::directory_iterator(dir)) {
        if (!entry.is_regular_file()) continue;
        if (entry.path().extension() != ".hpp") continue;
        if (entry.path().filename() == ".gitkeep") continue;
        if (std::find(expected_paths.begin(), expected_paths.end(), entry.path()) ==
            expected_paths.end()) {
            std::filesystem::remove(entry.path());
        }
    }
    return 0;
}

} // namespace

int main(int argc, char* argv[]) {
    if (argc >= 2) {
        return export_target_matrix(argv[1]);
    }

    ::boost::typelayout::SigExporter ex;
    xoffset::signature::add_exported_types(ex);
    ex.write_stdout();
    return 0;
}
